package com.patricksales.testwhitecard.features.detailsbook.model

data class PullRepository(
    val url: String?,
    val id: Int?,
    val node_id: String?,
    val html_url: String?,
    val diff_url: String?,
    val patch_url: String?,
    val issue_url: String?,
    val number: Int?,
    val state: String?,
    val locked: Boolean?,
    val title: String?,
    val user: UserXX,
    val body: String?,
    val created_at: String?,
    val updated_at: String?,
    val closed_at: String?,
    val merged_at: Any?,
    val merge_commit_sha: String?,
    val assignee: String?,
    val assignees: List<Any?>,
    val requested_reviewers: List<Any?>,
    val requested_teams: List<Any?>,
    val labels: List<Any?>,
    val milestone: Any?,
    val commits_url: String?,
    val review_comments_url: String?,
    val review_comment_url: String?,
    val comments_url: String?,
    val statuses_url: String?,
    val author_association: String?,
    val head: Head?,
    val base: Base?,
    val _links: Links?
)